Default: &defaults
  database: counter.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: counter_test.sqlite3
  <<: *defaults

Staging:
  database: counter_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: counter_production.sqlite3
  poolsize: 100
  <<: *defaults
